// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjqf1EeO8yCruIrtTBMTN-eel1wc1-J5I',
    appId: '1:414120529077:web:2f65ebc0fa217c3a6a02fc',
    messagingSenderId: '414120529077',
    projectId: 'todo-verynew-app',
    authDomain: 'todo-verynew-app.firebaseapp.com',
    storageBucket: 'todo-verynew-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAJY3bhMHo-Wch1Y7OiO5j3zDsyI0oBw',
    appId: '1:414120529077:android:877e7451dc4d80856a02fc',
    messagingSenderId: '414120529077',
    projectId: 'todo-verynew-app',
    storageBucket: 'todo-verynew-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi95EKfYSXZWslsAabsY8T2IU_1bOiwx4',
    appId: '1:414120529077:ios:95236455ad82743f6a02fc',
    messagingSenderId: '414120529077',
    projectId: 'todo-verynew-app',
    storageBucket: 'todo-verynew-app.firebasestorage.app',
    iosBundleId: 'com.example.todoVerynew',
  );

}